# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliWorld < Formula
  desc ""
  homepage "https://github.com/devenes/cli-world"
  version "0.0.2"

  on_macos do
    url "https://github.com/devenes/cli-world/releases/download/v0.0.2/cli-world_0.0.2_darwin_all.tar.gz"
    sha256 "dcad0777d79ab4ed2c28778f2610b473c7533a3cdbcc8df3f93adb818b854344"

    def install
      bin.install "cli-world"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenes/cli-world/releases/download/v0.0.2/cli-world_0.0.2_linux_arm64.tar.gz"
      sha256 "3918068ba80c5d05b393b8155e50ec479089be04bdbc4fbbbc4dfeb2c6110f54"

      def install
        bin.install "cli-world"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devenes/cli-world/releases/download/v0.0.2/cli-world_0.0.2_linux_amd64.tar.gz"
      sha256 "73ecea069d262a5ee71dc5e8fef9baa1b7fe64cf1603791231e78419fbf24fb3"

      def install
        bin.install "cli-world"
      end
    end
  end
end
