# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CliWorld < Formula
  desc ""
  homepage "https://github.com/devenes/cli-world"
  version "0.0.3"

  on_macos do
    url "https://github.com/devenes/cli-world/releases/download/v0.0.3/cli-world_0.0.3_darwin_all.tar.gz"
    sha256 "edb929f257a6037695c5001685d473ade77158967616e2c505c683a51ddf7f0b"

    def install
      bin.install "cli-world"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/devenes/cli-world/releases/download/v0.0.3/cli-world_0.0.3_linux_arm64.tar.gz"
      sha256 "71d37dc4666d46fd056adab34272861c6d2b4fbb85f481e9be003bb22526a33a"

      def install
        bin.install "cli-world"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/devenes/cli-world/releases/download/v0.0.3/cli-world_0.0.3_linux_amd64.tar.gz"
      sha256 "374b75f16e47b916776596867f2bd50ea8d909f0a3123caf4f75243bc08248ac"

      def install
        bin.install "cli-world"
      end
    end
  end
end
